---
- name: Converge
  hosts: all
  vars:
    role_name: "{{ lookup('env', 'BUILDKITE_BUILD_CHECKOUT_PATH') | default('ansible-netdata-binary', true) }}"
  roles:
    - role: "{{ role_name }}"
      netdata_config:
        global:
          history: 7200
